version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i npm@^8.3.2 -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build